test: &default

  # Credentials for REST APIs (VENDEDOR)
  client_id: AUVIwGHddHwmVRs42FIf-y0NLiTH4knassAQGNPP1xTYVnX3H74V9jQPW1dAmDmizK_v6TbOW-f3O_vT
  client_secret: EEGAfpy3GPsMPhEgFeDkoR7BqfJNaaB65R3jZhivE9xMfEuLoqrLdd49zIahk8p3n_yWBoyaHZYr7dir

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: patty1508_aleja@hotmail.com #nombre del vendedor

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  client_id: AaiWBKEv5i7WNdCPEfR3BnP0I5oZCOjArIfEcUnVQ4nK2NKJ1lnOMLEUjER-znlbAFg5ltkbymm-igm1
  client_secret: EL0MPqGzioCVoUmkcC3i64rCFlBg_3Lv_KkIVfcUn4limXh5JBgyNAXmq7fS7dc0_9GiuyyzdhpeTTEW
  mode: live
